---
deployment:
  tasks:
    # Direktori tujuan deployment di server cPanel
    - export DEPLOYPATH=/home/u1521077/public_html/artcamp.bimbelgambar.id

    # Pastikan folder tujuan ada
    - /bin/mkdir -p $DEPLOYPATH

    # Salin seluruh project kecuali folder yang tidak dibutuhkan di server
    - /bin/rsync -a --delete --exclude ".git" --exclude "node_modules" --exclude "public/storage" ./ $DEPLOYPATH/

    # Install dependensi Composer (gunakan opsi --no-dev agar ringan di produksi)
    - /usr/bin/php -d detect_unicode=0 /opt/cpanel/composer/bin/composer install --working-dir=$DEPLOYPATH --no-dev --optimize-autoloader --no-interaction

    # Jalankan migrasi database bila diperlukan (hapus jika tidak diinginkan)
    - /usr/bin/php $DEPLOYPATH/artisan migrate --force

    # Lewati proses build npm di server cPanel (asset hasil build diasumsikan dipush dari lokal)

    # Bersihkan cache agar konfigurasi/route/view terbaru digunakan
    - /usr/bin/php $DEPLOYPATH/artisan optimize:clear

    # Pastikan storage link tersedia
    - /usr/bin/php $DEPLOYPATH/artisan storage:link || true
